### ISSUE TITLE
11-Apr-2023 Peer-To-Peer Code Review

### ISSUE THREAD

**Issue by oovillagran** [CarlosIgreda/To-Do-list#4]
@CarlosIgreda You have performed an excellent job here. Congratulations. There are some small issues you can consider to put into your project:

- Please update the issue link in the README.md file.
- Please, kindly check the trash icon of your project, It seems that there is a trouble with some browsers where the icon is hidden.
- Please, check the edit task function, when an activity is marked it remains marked until you refresh the page.
- If you have time you can try to interactive between activities, and to move each other according to user preferences.

**Comment by CarlosIgreda** [comment]
@oovillagran Thanks for your suggestions, I appreciate them. 


![tufoin](https://media.giphy.com/media/xUNda5RSVWLzb5BET6/giphy.gif)
